/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--bg-main)',
        surface: 'var(--bg-surface)',
        panel: 'var(--bg-panel)',
        elevated: 'var(--bg-elevated)',
        overlay: 'var(--bg-overlay)',
        modal: 'var(--bg-modal)',
        foreground: 'var(--text-primary)',
        'muted-foreground': 'var(--text-secondary)',
        subtle: 'var(--text-muted)',
        border: 'var(--border-subtle)',
        'border-strong': 'var(--border-strong)',
        'hover-surface': 'var(--hover-bg)',
        'accent-surface': 'var(--accent-surface)',
        'nav-inactive': 'var(--nav-inactive)',
        'nav-inactive-hover': 'var(--nav-inactive-hover)',
        'nav-inactive-bg': 'var(--nav-inactive-bg)',
        'pill-bg': 'var(--pill-bg)',
        'pill-border': 'var(--pill-border)',
        'progress-track': 'var(--progress-track)',
        scrim: 'var(--modal-scrim)',
        'accent-cyan': 'var(--accent-cyan)',
        'accent-blue': 'var(--accent-blue)',
        'accent-amber': 'var(--accent-amber)',
      },
      fontFamily: {
        sans: ['var(--font-inter)', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['var(--font-mono)', 'JetBrains Mono', 'Fira Code', 'monospace'],
        display: ['var(--font-space)', 'var(--font-inter)', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fade-in 300ms ease-out both',
        'slide-up': 'slide-up 400ms ease-out both',
        'scale-in': 'scale-in 250ms ease-out both',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
